//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMouseControlFocus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoMouseControlFocus.ResTranslate", typeof(ResTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Press the OK button to download the new version.
        /// </summary>
        internal static string A_new_version_has_been_released__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("A new version has been released. Press the OK button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Would you like to download it now ?.
        /// </summary>
        internal static string A_new_version_has_been_released__Would_you_like_to_download_it_now__ {
            get {
                return ResourceManager.GetString("A new version has been released. Would you like to download it now ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured !.
        /// </summary>
        internal static string An_error_occured__ {
            get {
                return ResourceManager.GetString("An error occured !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new version ?.
        /// </summary>
        internal static string Download_new_version__ {
            get {
                return ResourceManager.GetString("Download new version ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not run new Setup File !.
        /// </summary>
        internal static string Error__Could_not_run_new_Setup_File__ {
            get {
                return ResourceManager.GetString("Error. Could not run new Setup File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not Save if Application will start automatically with Windows.
        /// </summary>
        internal static string Error__Could_not_Save_if_Application_will_start_automatically_with_Windows {
            get {
                return ResourceManager.GetString("Error. Could not Save if Application will start automatically with Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Could not change Language !.
        /// </summary>
        internal static string Error_Could_not_change_Language__ {
            get {
                return ResourceManager.GetString("Error Could not change Language !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free for Personal and Commercial Use - Please Donate !.
        /// </summary>
        internal static string Free_for_Personal_and_Commercial_Use___Please_Donate__ {
            get {
                return ResourceManager.GetString("Free for Personal and Commercial Use - Please Donate !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free for Personal Use Only - Please Donate !.
        /// </summary>
        internal static string Free_for_Personal_Use_Only___Please_Donate__ {
            get {
                return ResourceManager.GetString("Free for Personal Use Only - Please Donate !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great application to automaticallly focus on Control while you hover it with the mouse..
        /// </summary>
        internal static string Great_application_to_automaticallly_focus_on_Control_while_you_hover_it_with_the_mouse_ {
            get {
                return ResourceManager.GetString("Great application to automaticallly focus on Control while you hover it with the " +
                        "mouse.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, next times the application will run hidden, minimized to the Windows system tray, unless you uncheck the option Minimize to System Tray..
        /// </summary>
        internal static string However__next_times_the_application_will_run_hidden__minimized_to_the_Windows_system_tray__unless_you_uncheck_the_option_Minimize_to_System_Tray_ {
            get {
                return ResourceManager.GetString("However, next times the application will run hidden, minimized to the Windows sys" +
                        "tem tray, unless you uncheck the option Minimize to System Tray.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to upgrade to the latest version of the application. Press the OK button to download the new version.
        /// </summary>
        internal static string It_is_necessary_to_upgrade_to_the_latest_version_of_the_application__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("It is necessary to upgrade to the latest version of the application. Press the OK" +
                        " button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Class Name !.
        /// </summary>
        internal static string Please_enter_a_Class_Name__ {
            get {
                return ResourceManager.GetString("Please enter a Class Name !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application !.
        /// </summary>
        internal static string Please_restart_the_application__ {
            get {
                return ResourceManager.GetString("Please restart the application !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now exit and run the updated setup file.
        /// </summary>
        internal static string The_application_will_now_exit_and_run_the_updated_setup_file {
            get {
                return ResourceManager.GetString("The application will now exit and run the updated setup file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first time you run the application this settings window is being shown..
        /// </summary>
        internal static string The_first_time_you_run_the_application_this_settings_window_is_being_shown_ {
            get {
                return ResourceManager.GetString("The first time you run the application this settings window is being shown.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the latest version !.
        /// </summary>
        internal static string This_is_the_latest_version__ {
            get {
                return ResourceManager.GetString("This is the latest version !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified Error.
        /// </summary>
        internal static string Unspecified_Error {
            get {
                return ResourceManager.GetString("Unspecified Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
